baseurl = "http://example.org"
title = "Z. Michael Luo"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Web Dev, Software Engineer, Music Lover, Lifelong Learner<!--]-->'
  skills = "<!--[-->Skills: JavaScript, React, Redux, Ruby on Rails, HTML5, CSS3<!--]-->"
  initials = "Z.M.L"
  copyright = "Untitled"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/zluo16/"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@zluo"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/zluo16"
